### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by bcdavasconcelos** [cltk/greek_software_tlgu#2]
Hi,

I've been trying to run the code on OSX 10.14 but I keep getting this error: cannot execute binary file.
Any ideas as to why this might be happening?

**Comment by kylepjohnson** [comment]
Could you give me some more details? Please paste into here (a) the exact commands you run and (b) the full output created in the Terminal and (c) the contents of the file at `~/cltk_data/cltk.log`.

**Comment by kylepjohnson** [comment]
Also, do you only want to install TLGU? Or do you want to use and install it through the CLTK? If the latter, have you followed the directions here? http://docs.cltk.org/en/latest/importing_corpora.html

- First load the importer class with the Greek parameter: `CorpusImporter('greek')`
- Then install tlgu: `corpus_importer.import_corpus('greek_software_tlgu')`
- Then "import" your local corpus (this moves a copy into the `~/cltk_data` dir) : `corpus_importer.import_corpus('tlg', '~/Documents/corpora/TLG_E/')`
