### ISSUE TITLE
Possible bug in the reference citation (y-Level)

### ISSUE THREAD

**Issue by bcdavasconcelos** [cltk/greek_software_tlgu#5]
Hi. I couldn't find D. Marinakis contact details anywhere and no better place to report this.

While converting TLG0086.TXT, I noticed a mistake that invariably happens in the reference citation at the y-level. 
Below is a sample (it doesn't just happen in this particular spot but in many different places as well). Notice how it goes from 193a to 194a and then back to 193b (it should go from 193a to 193b and then to 194a). The same problem does not seem to occur while viewing the text in Diogenes.

```
193a.	              ἕνα μὲν οὖν τρόπον οὕτως ἡ φύσις λέγεται,  
193a.	ἡ πρώτη ἑκάστῳ ὑποκειμένη ὕλη τῶν ἐχόντων ἐν αὑτοῖς ἀρ-
193a.	χὴν κινήσεως καὶ μεταβολῆς, ἄλλον δὲ τρόπον ἡ μορφὴ 
193a.	καὶ τὸ εἶδος τὸ κατὰ τὸν λόγον. ὥσπερ γὰρ τέχνη λέγεται 
193a.	τὸ κατὰ τέχνην καὶ τὸ τεχνικόν, οὕτω καὶ φύσις τὸ κατὰ 
193a.	φύσιν [λέγεται] καὶ τὸ φυσικόν, οὔτε δὲ ἐκεῖ πω φαῖμεν ἂν 
193a.	ἔχειν κατὰ τὴν τέχνην οὐδέν, εἰ δυνάμει μόνον ἐστὶ κλίνη, μή 
193a.	πω δ' ἔχει τὸ εἶδος τῆς κλίνης, οὐδ' εἶναι τέχνην, οὔτ' ἐν 
193a.	τοῖς φύσει συνισταμένοις· τὸ γὰρ δυνάμει σὰρξ ἢ ὀστοῦν οὔτ' 
194a.	ἔχει πω τὴν ἑαυτοῦ φύσιν, πρὶν ἂν λάβῃ τὸ εἶδος τὸ κατὰ 
194a.	τὸν λόγον, ᾧ ὁριζόμενοι λέγομεν τί ἐστι σὰρξ ἢ ὀστοῦν, οὔτε 
194a.	φύσει ἐστίν. ὥστε ἄλλον τρόπον ἡ φύσις ἂν εἴη τῶν ἐχόντων 
194a.	ἐν αὑτοῖς κινήσεως ἀρχὴν ἡ μορφὴ καὶ τὸ εἶδος, οὐ χωρι-
194a.	στὸν ὂν ἀλλ' ἢ κατὰ τὸν λόγον. (τὸ δ' ἐκ τούτων φύσις μὲν 
194a.	οὐκ ἔστιν, φύσει δέ, οἷον ἄνθρωπος.) καὶ μᾶλλον αὕτη φύσις 
194a.	τῆς ὕλης· ἕκαστον γὰρ τότε λέγεται ὅταν ἐντελεχείᾳ ᾖ, 
194a.	μᾶλλον ἢ ὅταν δυνάμει. ἔτι γίγνεται ἄνθρωπος ἐξ ἀνθρώπου, 
194a.	ἀλλ' οὐ κλίνη ἐκ κλίνης· διὸ καί φασιν οὐ τὸ σχῆμα εἶναι 
194a.	τὴν φύσιν ἀλλὰ τὸ ξύλον, ὅτι γένοιτ' ἄν, εἰ βλαστάνοι, οὐ 
194a.	κλίνη ἀλλὰ ξύλον. εἰ δ' ἄρα τοῦτο φύσις, καὶ ἡ μορφὴ 
194a.	φύσις· γίγνεται γὰρ ἐξ ἀνθρώπου ἄνθρωπος. ἔτι δ' ἡ φύσις 
194a.	ἡ λεγομένη ὡς γένεσις ὁδός ἐστιν εἰς φύσιν. οὐ γὰρ ὥσπερ 
193b.	ἡ ἰάτρευσις λέγεται οὐκ εἰς ἰατρικὴν ὁδὸς ἀλλ' εἰς ὑγίειαν· 
193b.	ἀνάγκη μὲν γὰρ ἀπὸ ἰατρικῆς οὐκ εἰς ἰατρικὴν εἶναι τὴν ἰά-
193b.	τρευσιν, οὐχ οὕτω δ' ἡ φύσις ἔχει πρὸς τὴν φύσιν, ἀλλὰ τὸ 
193b.	φυόμενον ἐκ τινὸς εἰς τὶ ἔρχεται ᾗ φύεται. τί οὖν φύε-
193b.	ται; οὐχὶ ἐξ οὗ, ἀλλ' εἰς ὅ. ἡ ἄρα μορφὴ φύσις. ἡ δὲ 
193b.	μορφὴ καὶ ἡ φύσις διχῶς λέγεται· καὶ γὰρ ἡ στέρησις εἶ-
193b.	δός πώς ἐστιν.
```

I will dig around and see if I can find the cause, but I am not yet familiar with the code.
Cheers.

**Comment by bcdavasconcelos** [comment]
The bug was fixed in version 1.9 (27-Jul-2021). Thanks professor Marinakis.

(It remains in version 1.8 still used by CLTK).

**Comment by kylepjohnson** [comment]
I have updated to the latest tlgu version 1.9 (#6). Prof. Marinakis let me know about this, but unfortunately I have been very slow to update this.

@bcdavasconcelos Do you work much with the TLG? Looking to the future, I need help working on this. Would you like to help us keep this up-to-date and tested?

**Comment by bcdavasconcelos** [comment]
I would be happy to, @kylepjohnson. Just let me know what I can do.

**Comment by kylepjohnson** [comment]
@bcdavasconcelos I sent an email to the address on your website. Let me know if it did not come through!

**Comment by bcdavasconcelos** [comment]
@kylepjohnson, just to be sure, I had mailed you on Sunday already. Did it not come through?
