### ISSUE TITLE
running tlgu on Mac?

### ISSUE THREAD

**Issue by mlana** [cltk/greek_software_tlgu#7]
hi, if i try 
./tlgu 
on Mac i get an error 
exec format error: ./tlgu

any idea?
probably a trivial matter, but i am not so skilled in terminal work
Maurizio
(BTW: Mac M1 with MacOS v. 12.2.1)

**Comment by kylepjohnson** [comment]
Hi, I can try to help!

You can run TLGU as regular C code (directly from this repo) or through the CLTK (which installs it for you). Which of those two do you need?

On a Mac, you are going to need some "developer tools" to compile this code and then install it. I'll paste here how to compile and install yourself:

First download the code to your Downloads folder:
<img width="395" alt="Screen Shot 2022-06-29 at 8 33 50 AM" src="https://user-images.githubusercontent.com/1854968/176477108-0be4414b-1eae-49bd-bda3-a5923bf9d278.png">

Second use the Finder to unzip the .zip file.

Third go into that the TLGU folder with your Terminal: `cd ~/Downloads/grc_software_tlgu-master`

Fourth compile the software: `make all`. You may get an error here! If so, then copy-paste the entire error message here.

Finally "install" it: `make install`. You may need to add `sudo ` to the front of that command.

**Comment by kylepjohnson** [comment]
@mlana Closing this but reach out if you need anything else
